spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/damvuong/Spring-Cloud-Example
          searchPaths : part3-centralized-config/configuration/**